### ISSUE TITLE
Could you please increase level gain modifiers?

### ISSUE THREAD

**Issue by XanderSpecter** [XT-0xFF/MBAdjustableLeveling#1]
Hi!
For now, this mod allows to increase learning rate for skills to 1000%, which means just 10x scaling. So, it will be cool if modifier will become at least 100x :)

Thank you for this mod, it's a good mod :)

**Comment by ChrisF-127** [comment]
Sure, it just makes the slider a bit pointless, but that's fine with me. Already had it at 100x for my own testing, guess there's no harm to allow it for everyone!

**Comment by XanderSpecter** [comment]
In other mods I saw "number" sliders, they're also scales from 1 to 1000 but this is not percents, this is multiplier. I think that you can do the same - percents will become miltipliers and this can solve slider problem

**Comment by XanderSpecter** [comment]
But the negative factor of this method is impossibility to scale xp less than default x1 multiplier :(

**Comment by ChrisF-127** [comment]
100x modifier is now possible in version 1.0.2.0.
