### ISSUE TITLE
Minimum Learning Rate

### ISSUE THREAD

**Issue by Pib-k** [XT-0xFF/MBAdjustableLeveling#2]
Hey man, I love your mod so far. Could you add an adjustable minimum learning rate? So even if your learning limit/max skill for the amount of focus points and attribute points is reached, the learning rate will not be zero but instead be a value you choose yourself.

If you need any clarifications to what I mean let me know. If you're too buys I can also look into it and request a pull!

**Comment by ChrisF-127** [comment]
You mean, as in, being able to level for ever on, no matter the focus/attribute points?
I read that message on Steam, and it should not be too hard to implement, I was just thinking it pretty much defeats the whole point of having focus and attribute points.

Actually a lot more work to update and upload the new version of the mod than it is to actually create the version for this change...

**Comment by ChrisF-127** [comment]
Added settings for Minimum/Maximum Learning Rate in Version 1.0.3.1.
Only did a quick test, but it looked fine to me.
